import { expect, test } from '@playwright/test'
import path from 'node:path'

test('упрощённое демо открывает схему, тесты, предпросмотр и источники', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', 'Основной desktop-сценарий')
  await page.goto('/')
  await page.getByRole('button', { name: /Открыть полное демо/ }).click()
  await expect(page.getByLabel('Название воронки')).toHaveValue('7 внутренних механизмов')
  await expect(page.locator('.funnel-node')).toHaveCount(12)
  await expect(page.locator('.react-flow__minimap')).toHaveCount(0)
  await expect(page.getByRole('button', { name: /Рука — перемещать холст/ })).toHaveAttribute('aria-pressed', 'true')
  const viewport = page.locator('.react-flow__viewport')
  const viewportBeforePan = await viewport.getAttribute('style')
  const paneBox = await page.locator('.react-flow__pane').boundingBox()
  if (!paneBox) throw new Error('Холст не найден')
  await page.mouse.move(paneBox.x + paneBox.width * .65, paneBox.y + paneBox.height * .65)
  await page.mouse.down()
  await page.mouse.move(paneBox.x + paneBox.width * .65 + 70, paneBox.y + paneBox.height * .65 + 45, { steps: 4 })
  await page.mouse.up()
  await expect.poll(() => viewport.getAttribute('style')).not.toBe(viewportBeforePan)
  await page.getByRole('button', { name: /Выделение — выбирать и перемещать блоки/ }).click()
  await expect(page.getByRole('button', { name: /Выделение — выбирать и перемещать блоки/ })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.canvas-tool-select')).toBeVisible()
  await page.getByRole('button', { name: /Рука — перемещать холст/ }).click()
  await expect(page.locator('.canvas-tool-pan')).toBeVisible()

  await page.getByRole('button', { name: 'Тесты' }).click()
  await expect(page.getByRole('heading', { name: 'Психологические тесты' })).toBeVisible()
  await expect(page.getByText('7 внутренних механизмов', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'Результаты' }).click()
  await expect(page.getByText('Как выбирается результат')).toBeVisible()

  await page.getByRole('button', { name: 'Схема' }).click()
  await page.getByRole('button', { name: 'Предпросмотр' }).click()
  await expect(page.getByRole('dialog', { name: 'Предпросмотр воронки' })).toBeVisible()
  await page.getByRole('button', { name: 'Начать', exact: true }).click()
  await expect(page.getByText(/Здравствуйте! Пройдите короткую диагностику/)).toBeVisible()
  await page.getByRole('button', { name: 'Пройти тест' }).click()
  await page.getByRole('button', { name: 'Продолжить', exact: true }).click()
  await expect(page.getByText('Что вам важнее всего в сложной ситуации?')).toBeVisible()
  await page.getByLabel('Закрыть').click()

  await page.getByRole('button', { name: 'Статистика' }).click()
  await expect(page.getByRole('heading', { name: 'Как работает воронка' })).toBeVisible()
  await page.getByRole('button', { name: 'Источники' }).click()
  await expect(page.getByText('Instagram — Reels про тест')).toBeVisible()
  await expect(page.getByText('840', { exact: true })).toBeVisible()
})

test('старый расширенный fixture отклоняется понятным сообщением', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'mobile', 'Импорт проверяется один раз')
  await page.goto('/')
  await page.locator('input[type="file"]').setInputFiles(path.resolve('public/demo-7-mehanizmov-v1.funnel'))
  await expect(page.getByRole('heading', { name: 'Не удалось открыть файл' })).toBeVisible()
  await expect(page.getByText(/старой расширенной версии конструктора/)).toBeVisible()
})

test('мобильный интерфейс даёт доступ к блокам, настройкам сообщения и тестам', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Мобильная проверка')
  await page.goto('/')
  await page.getByRole('button', { name: /Открыть полное демо/ }).click()
  await expect(page.locator('.funnel-node').first()).toBeVisible()
  await page.getByRole('button', { name: 'Блоки', exact: true }).click()
  const drawer = page.locator('.mobile-drawer')
  await expect(drawer.getByRole('button', { name: /Сообщение/ })).toBeVisible()
  await expect(drawer.getByRole('button', { name: /Условие/ })).toHaveCount(0)
  await page.locator('.mobile-drawer-backdrop').click({ position: { x: 390, y: 20 } })

  await page.getByRole('button', { name: 'Тесты' }).click()
  await expect(page.getByRole('heading', { name: 'Психологические тесты' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Вопросы' })).toBeVisible()
})
